# use newer ubuntu versions
sudo: required
dist: precise
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
          packages:
            - gcc-5
            - g++-5
            - libsdl2-dev
            - cmake
      env:
        - COMPILER=g++-5
        - CC=gcc-5
        - CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
          packages:
            - clang-3.7
            - libsdl2-dev
            - cmake
      env:
        - COMPILER=clang++-3.7
        - CC=clang-3.7
        - CXX=clang++-3.7
script:
    - cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
    - make
